server:
  port: 8000

spring:
  application:
    # 服务名尽量用-，不用_，尽量不用特殊字符
    name: lab-http-client
  cloud:
    nacos:
      discovery:
        # 指定nacos的服务地址
        server-addr: 172.20.1.227:8848

feign:
  httpclient:
    # 让feign使用Apache HttpClient做请求
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50
  sentinel:
    enabled: true
  client:
    config:
      default:
        requestInterceptors:
          - ac.cn.saya.lab.http.handle.ToKenRelayRequestInterceptor

jwt:
  secret: vZ0N6kgV8UoMfM4YFZeXvzpmzWhADq1PUXcXdCa1Pi9AugCQdO0wKEubIpbp5xt7
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600


# 高德地图
amap:
  url: 12324
  key: 45657